# Generated by Django 3.2.9 on 2021-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_task', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('date_take_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата взятие заявки')),
                ('date_end_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заявки')),
                ('snils', models.CharField(max_length=20, verbose_name='Снилс')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone_task', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('telephone_contact', models.CharField(max_length=50, verbose_name='Телефон для обратной связи')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('time_call', models.CharField(max_length=150, verbose_name='Дата и время обратного звонка')),
                ('note', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='DepPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_task', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('date_take_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата взятие заявки')),
                ('date_end_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заявки')),
                ('snils', models.CharField(max_length=20, verbose_name='Снилс')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone_task', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('telephone_contact', models.CharField(max_length=50, verbose_name='Телефон для обратной связи')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('time_call', models.CharField(max_length=150, verbose_name='Дата и время обратного звонка')),
                ('note', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.CreateModel(
            name='DepPaySoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_task', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('date_take_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата взятие заявки')),
                ('date_end_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заявки')),
                ('snils', models.CharField(max_length=20, verbose_name='Снилс')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone_task', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('telephone_contact', models.CharField(max_length=50, verbose_name='Телефон для обратной связи')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('time_call', models.CharField(max_length=150, verbose_name='Дата и время обратного звонка')),
                ('note', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Соц.выплата',
                'verbose_name_plural': 'Соц.выплаты',
            },
        ),
        migrations.CreateModel(
            name='RayAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ray', models.CharField(max_length=60, verbose_name='Название района')),
                ('reduction_name_ray', models.CharField(max_length=20, verbose_name='Сокращение название района')),
                ('number_code_ray', models.CharField(max_length=20, verbose_name='Числовой код района')),
            ],
            options={
                'verbose_name': 'Район Назначения',
                'verbose_name_plural': 'Районы Назначения',
            },
        ),
        migrations.CreateModel(
            name='RayPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ray', models.CharField(max_length=60, verbose_name='Название района')),
                ('reduction_name_ray', models.CharField(max_length=20, verbose_name='Сокращение название района')),
                ('number_code_ray', models.CharField(max_length=20, verbose_name='Числовой код района')),
            ],
            options={
                'verbose_name': 'Район Выплаты',
                'verbose_name_plural': 'Районы Выплаты',
            },
        ),
        migrations.CreateModel(
            name='RayPaySoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ray', models.CharField(max_length=60, verbose_name='Название района')),
                ('reduction_name_ray', models.CharField(max_length=20, verbose_name='Сокращение название района')),
                ('number_code_ray', models.CharField(max_length=20, verbose_name='Числовой код района')),
            ],
            options={
                'verbose_name': 'Район Назначения',
                'verbose_name_plural': 'Районы Назначения',
            },
        ),
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=50, verbose_name='Имя статуса')),
                ('color_status', models.CharField(max_length=20, verbose_name='Цвет статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статус заявок',
            },
        ),
        migrations.CreateModel(
            name='ThemeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_theme_task', models.IntegerField(verbose_name='Id номер темы')),
                ('name_theme_task', models.CharField(max_length=400, verbose_name='Название темы')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('reduction_name_theme_task', models.CharField(max_length=25, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Тема заявки',
                'verbose_name_plural': 'Темы заявок',
            },
        ),
    ]
