# Generated by Django 3.2.9 on 2021-11-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_customs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raypaysoz',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_customs.customdepartments', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='raypay',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_customs.customdepartments', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='rayappointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_customs.customdepartments', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='deppaysoz',
            name='ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.rayappointment', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='deppaysoz',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.statustask', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='deppaysoz',
            name='theme_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.themetask', verbose_name='Тема заявки'),
        ),
        migrations.AddField(
            model_name='deppaysoz',
            name='user_close_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_close_task_pay_soz', to=settings.AUTH_USER_MODEL, verbose_name='Завершивший заявку'),
        ),
        migrations.AddField(
            model_name='deppaysoz',
            name='user_create_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_task_pay_soz', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='deppay',
            name='ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.raypay', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='deppay',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.statustask', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='deppay',
            name='user_close_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_close_task_pay', to=settings.AUTH_USER_MODEL, verbose_name='Завершивший заявку'),
        ),
        migrations.AddField(
            model_name='deppay',
            name='user_create_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_task_pay', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='depappointment',
            name='ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.rayappointment', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='depappointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.statustask', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='depappointment',
            name='user_close_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_close_task_appointment', to=settings.AUTH_USER_MODEL, verbose_name='Завершивший заявку'),
        ),
        migrations.AddField(
            model_name='depappointment',
            name='user_create_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_task_appointment', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
    ]
