# Generated by Django 3.2.9 on 2021-11-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_customs', '0001_initial'),
        ('task_feedback', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTaskPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_theme_task', models.IntegerField(verbose_name='Id номер темы')),
                ('name_theme_task', models.CharField(max_length=400, verbose_name='Название темы')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('reduction_name_theme_task', models.CharField(max_length=25, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Тема заявки Перс.учет',
                'verbose_name_plural': 'Темы заявок Перс.учета',
            },
        ),
        migrations.AlterModelOptions(
            name='themetask',
            options={'verbose_name': 'Тема заявки Соц.Выплат', 'verbose_name_plural': 'Темы заявок Соц.Выплаты'},
        ),
        migrations.CreateModel(
            name='RayPayPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ray', models.CharField(max_length=60, verbose_name='Название района')),
                ('reduction_name_ray', models.CharField(max_length=20, verbose_name='Сокращение название района')),
                ('number_code_ray', models.CharField(max_length=20, verbose_name='Числовой код района')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_customs.customdepartments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Район Перс.Учет',
                'verbose_name_plural': 'Районы Перс.Учета',
            },
        ),
        migrations.CreateModel(
            name='DepPayPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_task', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('date_take_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата взятие заявки')),
                ('date_end_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заявки')),
                ('snils', models.CharField(max_length=20, verbose_name='Снилс')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone_task', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('telephone_contact', models.CharField(max_length=50, verbose_name='Телефон для обратной связи')),
                ('reg_number', models.IntegerField(verbose_name='Рег.Номер')),
                ('reg_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование страхователя')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('time_call', models.CharField(max_length=150, verbose_name='Дата и время обратного звонка')),
                ('note', models.TextField(verbose_name='Примечание')),
                ('ray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.raypaypers', verbose_name='Район')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.statustask', verbose_name='Статус')),
                ('theme_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_feedback.themetaskpers', verbose_name='Темы Перс.Учёта')),
                ('user_close_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_close_task_pay_pers', to=settings.AUTH_USER_MODEL, verbose_name='Завершивший заявку')),
                ('user_create_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_task_pay_pers', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки')),
            ],
            options={
                'verbose_name': 'Перс.Учет',
                'verbose_name_plural': 'Перс.Учет',
            },
        ),
    ]
