# Generated by Django 3.2.9 on 2021-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_feedback', '0003_auto_20211121_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depappointment',
            options={'verbose_name': 'Задача Назначение', 'verbose_name_plural': 'Задачи Назначения'},
        ),
        migrations.AlterModelOptions(
            name='deppay',
            options={'verbose_name': 'Задача Выплата', 'verbose_name_plural': 'Задачи Выплаты'},
        ),
        migrations.AlterModelOptions(
            name='deppaypers',
            options={'verbose_name': 'Задача Перс.Учет', 'verbose_name_plural': 'Задачи Перс.Учет'},
        ),
        migrations.AlterModelOptions(
            name='deppaysoz',
            options={'verbose_name': 'Задача Соц.выплата', 'verbose_name_plural': 'Задачи Соц.выплаты'},
        ),
        migrations.AlterField(
            model_name='deppay',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
