# Generated by Django 3.2.9 on 2021-11-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_feedback', '0004_auto_20211123_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deppay',
            name='ray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_feedback.raypay', verbose_name='Район'),
        ),
    ]
