# Generated by Django 3.2.9 on 2021-11-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_feedback', '0005_alter_deppay_ray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deppay',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_feedback.statustask', verbose_name='Статус'),
        ),
    ]
